<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'Firehed\\Arctools\\Unit\\PHPUnitTestEngine' => 'Unit/PHPUnitTestEngine.php',
    'Firehed\\Arctools\\Unit\\ResultParser' => 'Unit/ResultParser.php',
    'Firehed\\Arctools\\Unit\\Printer' => 'Unit/Printer.php',
  ),
  'function' => array(),
  'xmap' => array(
    'Firehed\\Arctools\\Unit\\PHPUnitTestEngine' => 'ArcanistUnitTestEngine',
    'Firehed\\Arctools\\Unit\\ResultParser' => 'ArcanistTestResultParser',
  ),
));
